
import java.util.ArrayList;
import java.util.List;
import java.util.NoSuchElementException;
import java.util.Random;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
import labs.l1pack.labFirst;
import labs.l2pack.LabSecond;
import labs.l3pack.LabThird;
import labs.l4pack.Dict;
import labs.l5pack.LabFifth;
import labs.l6pack.State;
import labs.l6pack.Utils;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class appl7 extends javax.swing.JFrame {
    public class Process {
        private static State state = State.RUNNING;
        private static final Object mutex = new Object();
        private Thread abstractProgram = new Thread(new AbstractProgram());


        class AbstractProgram implements Runnable {

            @Override
            public void run() {
                Thread daemon = new Thread(() -> {
                    while (true) {
                        Utils.pause(1000, 5000);
                        if (abstractProgram.isInterrupted()) {
                            break;
                        }
                        synchronized (mutex) {
                            state = State.values()[new Random().nextInt(State.values().length)];
                            l6TextField.append("Daemon: abstract program state switched to " + state.toString()+'\n');
                            mutex.notify();
                        }
                    }
                });
                daemon.setDaemon(true);
                daemon.start();
                l6TextField.append("Abstract program: started working"+'\n');

                while (!Thread.currentThread().isInterrupted()) {
                    someWork();
                }
            }

            private void someWork() {
                int a = 0;
                a++;
            }
        }

        class Supervisor implements Runnable {

            @Override
            public void run() {
                l6TextField.append("Super visor: started working"+'\n');
                abstractProgram.start();
                while (!abstractProgram.isInterrupted()) {
                    synchronized (mutex) {
                        try {
                            mutex.wait();
                        } catch (InterruptedException e) {
                            e.printStackTrace();
                        }
                        switch (state) {
                            case FATAL_ERROR -> stopProgram();
                            case UNKNOWN, STOPPING -> runProgram();
                            default -> l6TextField.append("Super visor: nothing"+'\n');
                        }
                    }
                }
            }

            private void runProgram() {
                state = State.RUNNING;
                l6TextField.append("Super visor: abstract program is restarted"+'\n');
            }

            private void stopProgram() {
                abstractProgram.interrupt();
                l6TextField.append("Super visor: abstract program is stopped because of FATAL_ERROR"+'\n');
            }
        }

        public void strt() {
            new Thread(new Supervisor()).start();
        }
    }

    /**
     * Creates new form appl7
     */
    public appl7() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        l1Label1 = new javax.swing.JLabel();
        l1Label2 = new javax.swing.JLabel();
        l1textField1 = new javax.swing.JTextField();
        l1TextField2 = new javax.swing.JTextField();
        l1AddButton = new javax.swing.JButton();
        l1ChangeButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        l1Table = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        l2Label = new javax.swing.JLabel();
        l2Button = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        l2TextField2 = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        l3RButton1 = new javax.swing.JRadioButton();
        l3RButton2 = new javax.swing.JRadioButton();
        l3RButton3 = new javax.swing.JRadioButton();
        l3Button = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        l3TextField = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        l4TextField1 = new javax.swing.JTextField();
        l4TextField2 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        l4TextField3 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        l4Button2 = new javax.swing.JButton();
        l4Button1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        l5List = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        l5TextField2 = new javax.swing.JTextArea();
        l5Button = new javax.swing.JButton();
        l5TextField1 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        l6TextField = new javax.swing.JTextArea();
        l6Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        l1Label1.setText("Hero name");

        l1Label2.setText("Moving strategy");

        l1textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l1textField1ActionPerformed(evt);
            }
        });

        l1AddButton.setText("Add");
        l1AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l1AddButtonActionPerformed(evt);
            }
        });

        l1ChangeButton.setText("Change");
        l1ChangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l1ChangeButtonActionPerformed(evt);
            }
        });

        l1Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Strategy"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        l1Table.setEnabled(false);
        l1Table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(l1Table);
        if (l1Table.getColumnModel().getColumnCount() > 0) {
            l1Table.getColumnModel().getColumn(0).setResizable(false);
            l1Table.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(l1Label2)
                    .addComponent(l1Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(l1TextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l1textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l1AddButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(l1ChangeButton))
                .addContainerGap(137, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l1Label1)
                    .addComponent(l1textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l1AddButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l1Label2)
                    .addComponent(l1TextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l1ChangeButton))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(275, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("lab 1", jPanel2);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        l2Label.setText("Вывод");

        l2Button.setText("Do something");
        l2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l2ButtonActionPerformed(evt);
            }
        });

        l2TextField2.setColumns(20);
        l2TextField2.setRows(5);
        l2TextField2.setEnabled(false);
        jScrollPane2.setViewportView(l2TextField2);

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("getWidthMul x 2\ngetVolumeSum x 3\ncheckWidth x 4");
        jTextArea2.setEnabled(false);
        jScrollPane9.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 90, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(l2Label))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(l2Button)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(l2Button)
                .addGap(12, 12, 12)
                .addComponent(l2Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(194, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("lab 2", jPanel3);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        l3RButton1.setText("1. Млекопитающие, Ежовые, Кошачьи, Хищные");
        l3RButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l3RButton1ActionPerformed(evt);
            }
        });

        l3RButton2.setText("2. Хищные, Хордовые, Манулы, Кошачьи");
        l3RButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l3RButton2ActionPerformed(evt);
            }
        });

        l3RButton3.setText("3. Ежовые, Насекомоядные, Хищные, Хищные");
        l3RButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l3RButton3ActionPerformed(evt);
            }
        });

        l3Button.setText("Segregate");
        l3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l3ButtonActionPerformed(evt);
            }
        });

        l3TextField.setColumns(20);
        l3TextField.setRows(5);
        l3TextField.setEnabled(false);
        jScrollPane3.setViewportView(l3TextField);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(l3RButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(l3RButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(l3RButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addComponent(l3Button)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(l3RButton1)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l3RButton2)
                    .addComponent(l3Button))
                .addGap(20, 20, 20)
                .addComponent(l3RButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jTabbedPane1.addTab("lab 3", jPanel4);

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        l4TextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l4TextField1ActionPerformed(evt);
            }
        });

        l4TextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l4TextField2ActionPerformed(evt);
            }
        });

        l4TextField3.setEditable(false);
        l4TextField3.setColumns(20);
        l4TextField3.setRows(5);
        l4TextField3.setEnabled(false);
        jScrollPane5.setViewportView(l4TextField3);

        jLabel1.setText("словарь");

        jLabel2.setText("текст исходный");

        l4Button2.setText("перевести c англ");
        l4Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l4Button2ActionPerformed(evt);
            }
        });

        l4Button1.setText("добавить");
        l4Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l4Button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(l4TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(l4TextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(l4Button1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(l4Button2)
                .addGap(41, 41, 41))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l4TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l4TextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l4Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l4Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(203, 203, 203))
        );

        jTabbedPane1.addTab("lab 4", jPanel5);

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        l5List.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1", "2", "3", "4", "5", "6", "7" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        l5List.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                l5ListAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane6.setViewportView(l5List);

        jScrollPane7.setEnabled(false);

        l5TextField2.setColumns(20);
        l5TextField2.setRows(5);
        l5TextField2.setEnabled(false);
        jScrollPane7.setViewportView(l5TextField2);

        l5Button.setText("Apply");
        l5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l5ButtonActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("1. среднее значение\n2. _new_ + верхний регистр\n3. квадрат всех встречающихся\nодин раз элементов\n4. отсортированные строки\nс 1го введенного символа\n5. последний элемент\nили исключение\n6. сумма четных чисел или 0\");\n7. преобразование всех строк\nв Мар, где 1ый символ - ключ,\nостальные - значение");
        jTextArea1.setEnabled(false);
        jScrollPane4.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l5TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(l5Button)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(l5TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(l5Button)))
                        .addGap(108, 108, 108))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("lab 5", jPanel6);

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));

        l6TextField.setColumns(20);
        l6TextField.setRows(5);
        l6TextField.setEnabled(false);
        jScrollPane8.setViewportView(l6TextField);

        l6Button.setText("Start");
        l6Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l6ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(l6Button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(l6Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("lab 6", jPanel7);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void l4Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l4Button1ActionPerformed
        Dict.load(l4TextField1.getText());
        l4TextField1.setText("");
    }//GEN-LAST:event_l4Button1ActionPerformed

    private void l4Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l4Button2ActionPerformed
        String s = Dict.translateText(l4TextField2.getText());
        l4TextField3.setText(s);
    }//GEN-LAST:event_l4Button2ActionPerformed

    private void l4TextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l4TextField2ActionPerformed

    }//GEN-LAST:event_l4TextField2ActionPerformed

    private void l4TextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l4TextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_l4TextField1ActionPerformed

    private void l3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l3ButtonActionPerformed
        if(l3RButton1.isSelected()){
            l3TextField.setText(LabThird.example1());
        }
        else if(l3RButton2.isSelected()){
            l3TextField.setText(LabThird.example2());
        }
        else if(l3RButton3.isSelected()){
            l3TextField.setText(LabThird.example3());
        }
    }//GEN-LAST:event_l3ButtonActionPerformed

    private void l3RButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l3RButton3ActionPerformed
        if(l3RButton3.isSelected()){
            l3RButton2.setSelected(false);
            l3RButton1.setSelected(false);
        }
    }//GEN-LAST:event_l3RButton3ActionPerformed

    private void l3RButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l3RButton2ActionPerformed
        if(l3RButton2.isSelected()){
            l3RButton1.setSelected(false);
            l3RButton3.setSelected(false);
        }
    }//GEN-LAST:event_l3RButton2ActionPerformed

    private void l3RButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l3RButton1ActionPerformed
        if(l3RButton1.isSelected()){
            l3RButton2.setSelected(false);
            l3RButton3.setSelected(false);
        }
    }//GEN-LAST:event_l3RButton1ActionPerformed

    private void l2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l2ButtonActionPerformed
        l2TextField2.setText(LabSecond.doLab());
    }//GEN-LAST:event_l2ButtonActionPerformed

    private void l1ChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l1ChangeButtonActionPerformed
        String name = l1textField1.getText();
        String str = l1TextField2.getText();
        DefaultTableModel model = (DefaultTableModel) l1Table.getModel();
        for (int i = 0; i< l1Table.getRowCount(); i++){
            if(l1Table.getValueAt(i, 0).equals(name)){
                if (labFirst.changeStrategy(name, str)){
                    model.setValueAt(labFirst.getStrategy(name), i, 1);
                }
            }
        }
        l1TextField2.setText("");
    }//GEN-LAST:event_l1ChangeButtonActionPerformed

    private void l1AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l1AddButtonActionPerformed
        String name = l1textField1.getText();
        String str = l1TextField2.getText();
        if (labFirst.addHero(name, str)){
            DefaultTableModel model = (DefaultTableModel) l1Table.getModel();
            model.addRow(new Object[]{name, labFirst.getStrategy(name)});
        }

    }//GEN-LAST:event_l1AddButtonActionPerformed

    private void l1textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l1textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_l1textField1ActionPerformed

    private void l5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l5ButtonActionPerformed
        if(null != l5List.getSelectedValue())switch (l5List.getSelectedValue().toString()) {
            case "1":
                l5TextField2.setText(LabFifth.task1(l5TextField1.getText()));
                l5TextField1.setText("");
                break;
            case "2":
                l5TextField2.setText(LabFifth.task2(l5TextField1.getText()));
                l5TextField1.setText("");
                break;
            case "3":
                l5TextField2.setText(LabFifth.task3(l5TextField1.getText()));
                l5TextField1.setText("");
                break;
            case "4":
                char c = l5TextField1.getText().charAt(0);
                l5TextField2.setText(LabFifth.task4(l5TextField1.getText().substring(2, l5TextField1.getText().length()), c));
                l5TextField1.setText("");
                break;
            case "5":
//                if(!l5TextField1.getText().isEmpty()){
                    try{
                        l5TextField2.setText(LabFifth.task5(l5TextField1.getText()));
                    }
                    catch(NoSuchElementException e){
                        l5TextField2.setText(e.getMessage());
                    }
                    l5TextField1.setText("");
                
                break;
            case "6":
                l5TextField2.setText(LabFifth.task6(l5TextField1.getText()));
                l5TextField1.setText("");
                break;
            case "7":
                l5TextField2.setText(LabFifth.task7(l5TextField1.getText()));
                l5TextField1.setText("");
                break;
            default:
                break;
        }
    }//GEN-LAST:event_l5ButtonActionPerformed

    private void l5ListAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_l5ListAncestorAdded
        
    }//GEN-LAST:event_l5ListAncestorAdded

    private void l6ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l6ButtonActionPerformed
        l6TextField.setText("");
        Process process = new Process();
        process.strt();
    }//GEN-LAST:event_l6ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(appl7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(appl7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(appl7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(appl7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new appl7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JButton l1AddButton;
    private javax.swing.JButton l1ChangeButton;
    private javax.swing.JLabel l1Label1;
    private javax.swing.JLabel l1Label2;
    private javax.swing.JTable l1Table;
    private javax.swing.JTextField l1TextField2;
    private javax.swing.JTextField l1textField1;
    private javax.swing.JButton l2Button;
    private javax.swing.JLabel l2Label;
    private javax.swing.JTextArea l2TextField2;
    private javax.swing.JButton l3Button;
    private javax.swing.JRadioButton l3RButton1;
    private javax.swing.JRadioButton l3RButton2;
    private javax.swing.JRadioButton l3RButton3;
    private javax.swing.JTextArea l3TextField;
    private javax.swing.JButton l4Button1;
    private javax.swing.JButton l4Button2;
    private javax.swing.JTextField l4TextField1;
    private javax.swing.JTextField l4TextField2;
    private javax.swing.JTextArea l4TextField3;
    private javax.swing.JButton l5Button;
    private javax.swing.JList<String> l5List;
    private javax.swing.JTextField l5TextField1;
    private javax.swing.JTextArea l5TextField2;
    private javax.swing.JButton l6Button;
    private javax.swing.JTextArea l6TextField;
    // End of variables declaration//GEN-END:variables
}
